config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:edit, :index, :show, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# before_action :correct_user, only: [:edit, :update]
  def new
    @book = Book.new
  end


  def create
    @user = current_user
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @books = Book.all
    @book = Book.new(book_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'Created book successfully'
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Updated successfully'
    else
      render :edit
    end
  end



  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
     redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :signed_in_user, only: [:edit, :update]
  # before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
     redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: 'Updated successfully'
    else
      render :edit
    end
  end

  # def signed_in_user
  #   render :edit
  # end

  private
  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end



end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
          </tr>
          <tr>
            <th>name</th>
    	      <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <div class=row>
      <h2>New book</h2>
      <%= form_with(model: book, local: true) do |f| %>
      <label for="book_title">Title</label><br>
      <%= f.text_field :title %><br>
      <label for="book_opinion">Opinion</label><br>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book' %>
      <% end %>
  </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<%= @book.errors.count %>error
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <%= form_with(model:@book, local: true, method: :patch) do |f| %>
        <label for="book_title">Title</label><br>
        <%= f.text_field :title, autofocus: true, id:"book_title"%><br>
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body, autofocus:true, id:"book_body" %><br>
        <%= f.submit "Update Book" %><br><br>
        <%=link_to "Show", book_path(@book.id) %>
        |
        <%=link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class=container>
  <div class=row>
    <div class=col-md-3>

      <% if @book.errors.any? %>
      <%= @book.errors.count %>error
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= render 'list', user: @user, book: @book %>
    </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user_id) do %>
                      <%= image_tag book.user.get_profile_image(50, 50) %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td colspan="3"></td>
              </tr>
             <% end %>
           </tbody>
          </table>
        </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with(model: @book, local: true) do |f| %>
<label for="book_title">Title</label><br>
<%= f.text_field :title %><br>
<label for="book_opinion">Opinion</label><br>
<%= f.text_area :body %><br>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class=container>
  <div class=row>
    <div class=col-md-3>
      <%= render 'list',book: @newbook, user: @user %>
    </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td colspan="3">
                <td><%= link_to user_path(@book.user_id) do %>
                      <%= image_tag @book.user.get_profile_image(50, 50) %>
                      <%= @book.user.name %>
                    <% end %>
                </td>
                <td><%= link_to @book.title, book_path(@book.id) %></td>
                <td><%= @book.body %></td>

                 <% if @book.user == current_user %>
                   <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
              　    <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
              　 <% end %>
              　 </td>
               </tr>
           </tbody>
          </table>
        </div>
      </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!</h1>
    </div>
  </div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div button class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                 <span class="fas fa-home home-btn text-light: :before"></span>
                 Home
                <% end %>
              </li>
              </li>
              <li>
                <%= link_to("/users") do %>
                 <span class="fas fa-users users-btn text-light: :before"></span>
                 Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                 <span class="fas fa-book-open book-open-btn text-light: :before"></span>
                 Books
                <% end %>
              </li>
              <li>
                <%= link_to("/users/sign_out",method: :delete) do %>
                 <span class="fas fa-sign-out-alt sign-out-alt-btn text-light: :before"></span>
                 Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to("/") do %>
                 <span class="fas fa-home home-btn text-light: :before"></span>
                 Home
                <% end %>
              </li>
              <li>
                <%= link_to("/home/about") do %>
                 <span class="fas fa-link link-btn text-light: :before"></span>
                About
                <% end %>
              </li>
              <li>
                <%= link_to("/users/sign_up") do %>
                 <span class="fas fa-user-plus user-plus-btn text-light: :before"></span>
                Sign up
                <% end %>
              </li>
              <li>
                <%= link_to("/users/sign_in") do %>
                 <span class="fas fa-sign-in-alt sign-in-alt-btn text-light: :before"></span>
                Log in
                <% end %>
              </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<%= @user.errors.count %>error
<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with(model:@user, local: true, method: :patch) do |f| %>
        <label for="user_name">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"user_name" %><br>
        <label for="user_image">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
        <label for="user_introduction">Introduction</label><br>
        <%= f.text_area :introduction, autofocus:true, id:"user_introduction", maxlength: "50" %><br>
        <%= f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class=row>
    <div class=col-md-3>
      <%= render 'books/list', user: @user, book: @book %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
            <td><%= image_tag user.get_profile_image(50, 50) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class=container>
  <div class=row>
    <div class=col-md-3>
      <%= render 'books/list', user: @user, book: @book %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user_id) do %>
                      <%= image_tag book.user.get_profile_image(50, 50) %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td colspan="3"></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
  </div>
</div>